import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  ar: {
    // Navigation
    companyName: 'ال عامر للألوميتال',
    createOrder: 'إنشاء طلب جديد',
    viewOrders: 'عرض جميع الطلبات',
    statistics: 'الإحصائيات',
    
    // Create Order Page
    createNewOrder: 'إنشاء طلب جديد',
    updateOrder: 'تحديث الطلب',
    customerName: 'اسم العميل',
    enterCustomerName: 'أدخل اسم العميل',
    orderDetails: 'تفاصيل الطلب',
    item: 'عنصر',
    deleteItem: 'حذف العنصر',
    width: 'العرض',
    length: 'الطول',
    area: 'المساحة',
    quantity: 'الكمية',
    category: 'الفئة',
    pricePerMeter: 'سعر المتر',
    total: 'الإجمالي',
    notes: 'ملاحظات',
    description: 'الوصف',
    chooseCategory: 'اختر الفئة',
    windows: 'نوافذ',
    doors: 'أبواب',
    kitchens: 'مطابخ',
    windows2: 'شبابيك',
    other: 'أخرى',
    anyAdditionalNotes: 'أي ملاحظات إضافية...',
    addNewItem: 'إضافة عنصر جديد',
    grandTotal: 'الإجمالي الكلي',
    advancePayment: 'دفعة مقدمة',
    enterAdvancePayment: 'أدخل الدفعة المقدمة',
    totalBeforeAdvance: 'الإجمالي قبل الدفعة المقدمة',
    totalAfterAdvance: 'الإجمالي بعد الدفعة المقدمة',
    remainingAmount: 'المبلغ المتبقي',
    details: 'التفاصيل',
    firstAdvancePayment: 'الدفعة المقدمة الأولى',
    secondAdvancePayment: 'الدفعة المقدمة الثانية',
    thirdAdvancePayment: 'الدفعة المقدمة الثالثة',
    fourthAdvancePayment: 'الدفعة المقدمة الرابعة',
    fifthAdvancePayment: 'الدفعة المقدمة الخامسة',
    sixthAdvancePayment: 'الدفعة المقدمة السادسة',
    seventhAdvancePayment: 'الدفعة المقدمة السابعة',
    eighthAdvancePayment: 'الدفعة المقدمة الثامنة',
    ninthAdvancePayment: 'الدفعة المقدمة التاسعة',
    tenthAdvancePayment: 'الدفعة المقدمة العاشرة',
    enterFirstAdvancePayment: 'أدخل الدفعة المقدمة الأولى',
    enterSecondAdvancePayment: 'أدخل الدفعة المقدمة الثانية',
    enterThirdAdvancePayment: 'أدخل الدفعة المقدمة الثالثة',
    enterFourthAdvancePayment: 'أدخل الدفعة المقدمة الرابعة',
    enterFifthAdvancePayment: 'أدخل الدفعة المقدمة الخامسة',
    enterSixthAdvancePayment: 'أدخل الدفعة المقدمة السادسة',
    enterSeventhAdvancePayment: 'أدخل الدفعة المقدمة السابعة',
    enterEighthAdvancePayment: 'أدخل الدفعة المقدمة الثامنة',
    enterNinthAdvancePayment: 'أدخل الدفعة المقدمة التاسعة',
    enterTenthAdvancePayment: 'أدخل الدفعة المقدمة العاشرة',
    firstAdvanceDate: 'تاريخ الدفعة الأولى',
    secondAdvanceDate: 'تاريخ الدفعة الثانية',
    thirdAdvanceDate: 'تاريخ الدفعة الثالثة',
    fourthAdvanceDate: 'تاريخ الدفعة الرابعة',
    fifthAdvanceDate: 'تاريخ الدفعة الخامسة',
    sixthAdvanceDate: 'تاريخ الدفعة السادسة',
    seventhAdvanceDate: 'تاريخ الدفعة السابعة',
    eighthAdvanceDate: 'تاريخ الدفعة الثامنة',
    ninthAdvanceDate: 'تاريخ الدفعة التاسعة',
    tenthAdvanceDate: 'تاريخ الدفعة العاشرة',
    addAdvancePayment: 'إضافة دفعة مقدمة',
    removeAdvancePayment: 'حذف الدفعة المقدمة',
    address: 'العنوان',
    enterAddress: 'أدخل عنوان العميل',
    residualAmount: 'المبلغ المتبقي',
    saveOrder: 'حفظ الطلب',
    saving: 'جاري الحفظ...',
    viewAllOrders: 'عرض جميع الطلبات',
    meter: 'متر',
    centimeter: 'سم',
    squareMeter: 'م²',
    squareCentimeter: 'سم²',
    currency: 'جنيه',
    unit: 'الوحدة',
    selectUnit: 'اختر الوحدة',
    
    // Orders List Page
    allOrders: 'جميع الطلبات',
    searchOrders: 'البحث في الطلبات...',
    exportToJSON: 'تصدير إلى JSON',
    importFromJSON: 'استيراد من JSON',
    customer: 'اسم العميل',
    numberOfItems: 'عدد العناصر',
    totalAmount: 'الإجمالي',
    creationDate: 'تاريخ الإنشاء',
    actions: 'الإجراءات',
    view: 'عرض',
    update: 'تحديث',
    delete: 'حذف',
    noOrdersFound: 'لا توجد طلبات تطابق البحث',
    noOrdersYet: 'لا توجد طلبات بعد',
    ordersSummary: 'ملخص الطلبات',
    totalOrders: 'إجمالي الطلبات',
    totalAmount2: 'إجمالي المبلغ',
    loading: 'جاري التحميل...',
    
    // Order View Page
    orderDetails2: 'تفاصيل الطلب',
    generatePDFInvoice: 'إنشاء فاتورة PDF',
    deleteOrder: 'حذف الطلب',
    backToOrders: 'العودة للطلبات',
    orderNotFound: 'الطلب غير موجود',
    backToOrders2: 'العودة للطلبات',
    invoice: 'فاتورة طلب',
    orderDate: 'تاريخ الطلب',
    customerData: 'بيانات العميل',
    name: 'الاسم',
    orderNumber: 'رقم الطلب',
    creationDate2: 'تاريخ الإنشاء',
    orderDetails3: 'تفاصيل الطلب',
    grandTotal2: 'الإجمالي الكلي',
    numberOfItems2: 'عدد العناصر',
    thankYou: 'شكراً لاختياركم خدماتنا',
    allRightsReserved: 'ال عامر للألوميتال - جميع الحقوق محفوظة',
    
    // Messages
    pleaseEnterCustomerName: 'يرجى إدخال اسم العميل',
    pleaseFillAllRequiredFields: 'يرجى ملء جميع الحقول المطلوبة',
    orderCreatedSuccessfully: 'تم إنشاء الطلب بنجاح!',
    orderUpdatedSuccessfully: 'تم تحديث الطلب بنجاح!',
    errorCreatingOrder: 'حدث خطأ أثناء إنشاء الطلب',
    errorUpdatingOrder: 'حدث خطأ أثناء تحديث الطلب',
    errorLoadingOrders: 'حدث خطأ أثناء تحميل الطلبات',
    orderDeletedSuccessfully: 'تم حذف الطلب بنجاح',
    errorDeletingOrder: 'حدث خطأ أثناء حذف الطلب',
        confirmDeleteOrder: 'هل أنت متأكد من حذف هذا الطلب؟',
        thisActionCannotBeUndone: 'هذا الإجراء لا يمكن التراجع عنه',
        cancel: 'إلغاء',
        deleting: 'جاري الحذف',
    dataExportedSuccessfully: 'تم تصدير البيانات بنجاح',
    errorExportingData: 'حدث خطأ أثناء تصدير البيانات',
    dataImportedSuccessfully: 'تم استيراد البيانات بنجاح',
    errorImportingData: 'حدث خطأ أثناء استيراد البيانات',
    invalidFile: 'ملف غير صالح',
    invoiceGeneratedSuccessfully: 'تم إنشاء الفاتورة بنجاح',
    errorGeneratingInvoice: 'حدث خطأ أثناء إنشاء الفاتورة',
    errorLoadingOrder: 'حدث خطأ أثناء تحميل الطلب',
    orderNotFound2: 'الطلب غير موجود',
    
    // Statistics Page
    refresh: 'تحديث',
    totalCustomers: 'إجمالي العملاء',
    totalRevenue: 'إجمالي الإيرادات',
    averageOrderValue: 'متوسط قيمة الطلب',
    
    // Status and User Management
    status: 'الحالة',
    working: 'قيد العمل',
    done: 'مكتمل',
    toggleStatus: 'تغيير الحالة',
    selectAll: 'تحديد الكل',
    deselectAll: 'إلغاء تحديد الكل',
    generateSelectedInvoice: 'إنشاء فاتورة للمحدد',
    selectItemsForInvoice: 'اختر العناصر للفاتورة',
    itemsSelected: 'عنصر محدد',
    selectedItems: 'العناصر المحددة',
    usersManagement: 'إدارة المستخدمين',
    manageUsers: 'إدارة المستخدمين',
    deleteUser: 'حذف المستخدم',
    confirmDeleteUser: 'هل أنت متأكد من حذف هذا المستخدم؟',
    userDeletedSuccessfully: 'تم حذف المستخدم بنجاح',
    errorDeletingUser: 'حدث خطأ أثناء حذف المستخدم',
    noUsersFound: 'لا يوجد مستخدمين',
    userOrdersCount: 'عدد الطلبات',
    cannotDeleteUserWithOrders: 'لا يمكن حذف مستخدم لديه طلبات',
    usersManagementNote: 'ملاحظة: لا يمكن حذف المستخدمين الذين لديهم طلبات مرتبطة بهم',
    orderSummary: 'ملخص الطلب',
    close: 'إغلاق',
    viewOrderDetails: 'عرض تفاصيل الطلب',
    clickViewDetailsToManageItems: 'انقر على "عرض تفاصيل الطلب" لإدارة العناصر وتغيير الحالة',
    clickGenerateInvoiceToManageItems: 'انقر على "إنشاء فاتورة PDF" لعرض تفاصيل الطلب وإدارة العناصر',
    storageInformation: 'معلومات التخزين',
    estimatedDataSize: 'حجم البيانات المقدر',
    browserStorageUsed: 'مساحة التخزين المستخدمة',
    browserStorageAvailable: 'مساحة التخزين المتاحة',
    usagePercentage: 'نسبة الاستخدام',
    storageDetails: 'تفاصيل التخزين',
    storageLocation: 'موقع التخزين',
    browserIndexedDB: 'متصفح (IndexedDB)',
    browserLimit: 'حد المتصفح',
    chromeLimit: '~80% من مساحة القرص المتاحة',
    firefoxLimit: '~50% من مساحة القرص المتاحة',
    safariLimit: '~1GB (iOS) / ~5GB (macOS)',
    edgeLimit: '~80% من مساحة القرص المتاحة',
    variesByBrowser: 'يختلف حسب المتصفح',
    dataPersistence: 'استمرارية البيانات',
    localToEachDevice: 'محلي لكل جهاز',
    backupMethod: 'طريقة النسخ الاحتياطي',
    useExportImportFeature: 'استخدم ميزة التصدير/الاستيراد',
    ordersByCategory: 'الطلبات حسب الفئة',
    ordersByMonth: 'الطلبات حسب الشهر',
    topCustomers: 'أفضل العملاء',
    orders: 'طلبات',
    uncategorized: 'غير مصنف',
    importantNotes: 'ملاحظات مهمة',
    dataStoredLocally: 'البيانات مخزنة محلياً في متصفحك فقط',
    clearingBrowserDataWarning: 'مسح بيانات المتصفح سيحذف جميع الطلبات',
    dataDoesNotSync: 'البيانات لا تزامن بين الأجهزة',
    regularExportsRecommended: 'يُنصح بالتصدير المنتظم للنسخ الاحتياطي'
  },
  en: {
    // Navigation
    companyName: 'Al-Amer for Aluminum',
    createOrder: 'Create New Order',
    viewOrders: 'View All Orders',
    statistics: 'Statistics',
    
    // Create Order Page
    createNewOrder: 'Create New Order',
    updateOrder: 'Update Order',
    customerName: 'Customer Name',
    enterCustomerName: 'Enter customer name',
    orderDetails: 'Order Details',
    item: 'Item',
    deleteItem: 'Delete Item',
    width: 'Width',
    length: 'Length',
    area: 'Area',
    quantity: 'Quantity',
    category: 'Category',
    pricePerMeter: 'Price per Meter',
    total: 'Total',
    notes: 'Notes',
    description: 'Description',
    chooseCategory: 'Choose Category',
    windows: 'Windows',
    doors: 'Doors',
    kitchens: 'Kitchens',
    windows2: 'Window Frames',
    other: 'Other',
    anyAdditionalNotes: 'Any additional notes...',
    addNewItem: 'Add New Item',
    grandTotal: 'Grand Total',
    advancePayment: 'Advance Payment',
    enterAdvancePayment: 'Enter advance payment',
    totalBeforeAdvance: 'Total Before Advance',
    totalAfterAdvance: 'Total After Advance',
    remainingAmount: 'Remaining Amount',
    details: 'Details',
    firstAdvancePayment: 'First Advance Payment',
    secondAdvancePayment: 'Second Advance Payment',
    thirdAdvancePayment: 'Third Advance Payment',
    fourthAdvancePayment: 'Fourth Advance Payment',
    fifthAdvancePayment: 'Fifth Advance Payment',
    sixthAdvancePayment: 'Sixth Advance Payment',
    seventhAdvancePayment: 'Seventh Advance Payment',
    eighthAdvancePayment: 'Eighth Advance Payment',
    ninthAdvancePayment: 'Ninth Advance Payment',
    tenthAdvancePayment: 'Tenth Advance Payment',
    enterFirstAdvancePayment: 'Enter first advance payment',
    enterSecondAdvancePayment: 'Enter second advance payment',
    enterThirdAdvancePayment: 'Enter third advance payment',
    enterFourthAdvancePayment: 'Enter fourth advance payment',
    enterFifthAdvancePayment: 'Enter fifth advance payment',
    enterSixthAdvancePayment: 'Enter sixth advance payment',
    enterSeventhAdvancePayment: 'Enter seventh advance payment',
    enterEighthAdvancePayment: 'Enter eighth advance payment',
    enterNinthAdvancePayment: 'Enter ninth advance payment',
    enterTenthAdvancePayment: 'Enter tenth advance payment',
    firstAdvanceDate: 'First Payment Date',
    secondAdvanceDate: 'Second Payment Date',
    thirdAdvanceDate: 'Third Payment Date',
    fourthAdvanceDate: 'Fourth Payment Date',
    fifthAdvanceDate: 'Fifth Payment Date',
    sixthAdvanceDate: 'Sixth Payment Date',
    seventhAdvanceDate: 'Seventh Payment Date',
    eighthAdvanceDate: 'Eighth Payment Date',
    ninthAdvanceDate: 'Ninth Payment Date',
    tenthAdvanceDate: 'Tenth Payment Date',
    addAdvancePayment: 'Add Advance Payment',
    removeAdvancePayment: 'Remove Advance Payment',
    address: 'Address',
    enterAddress: 'Enter customer address',
    residualAmount: 'Residual Amount',
    saveOrder: 'Save Order',
    saving: 'Saving...',
    viewAllOrders: 'View All Orders',
    meter: 'm',
    centimeter: 'cm',
    squareMeter: 'm²',
    squareCentimeter: 'cm²',
    currency: 'EGP',
    unit: 'Unit',
    selectUnit: 'Select Unit',
    
    // Orders List Page
    allOrders: 'All Orders',
    searchOrders: 'Search orders...',
    exportToJSON: 'Export to JSON',
    importFromJSON: 'Import from JSON',
    customer: 'Customer',
    numberOfItems: 'Number of Items',
    totalAmount: 'Total Amount',
    creationDate: 'Creation Date',
    actions: 'Actions',
    view: 'View',
    update: 'Update',
    delete: 'Delete',
    noOrdersFound: 'No orders match the search',
    noOrdersYet: 'No orders yet',
    ordersSummary: 'Orders Summary',
    totalOrders: 'Total Orders',
    totalAmount2: 'Total Amount',
    loading: 'Loading...',
    
    // Order View Page
    orderDetails2: 'Order Details',
    generatePDFInvoice: 'Generate PDF Invoice',
    deleteOrder: 'Delete Order',
    backToOrders: 'Back to Orders',
    orderNotFound: 'Order not found',
    backToOrders2: 'Back to Orders',
    invoice: 'Order Invoice',
    orderDate: 'Order Date',
    customerData: 'Customer Data',
    name: 'Name',
    orderNumber: 'Order Number',
    creationDate2: 'Creation Date',
    orderDetails3: 'Order Details',
    grandTotal2: 'Grand Total',
    numberOfItems2: 'Number of Items',
    thankYou: 'Thank you for choosing our services',
    allRightsReserved: 'Al-Amer for Aluminum - All rights reserved',
    
    // Messages
    pleaseEnterCustomerName: 'Please enter customer name',
    pleaseFillAllRequiredFields: 'Please fill all required fields',
    orderCreatedSuccessfully: 'Order created successfully!',
    orderUpdatedSuccessfully: 'Order updated successfully!',
    errorCreatingOrder: 'Error creating order',
    errorUpdatingOrder: 'Error updating order',
    errorLoadingOrders: 'Error loading orders',
    orderDeletedSuccessfully: 'Order deleted successfully',
    errorDeletingOrder: 'Error deleting order',
        confirmDeleteOrder: 'Are you sure you want to delete this order?',
        thisActionCannotBeUndone: 'This action cannot be undone',
        cancel: 'Cancel',
        deleting: 'Deleting',
    dataExportedSuccessfully: 'Data exported successfully',
    errorExportingData: 'Error exporting data',
    dataImportedSuccessfully: 'Data imported successfully',
    errorImportingData: 'Error importing data',
    invalidFile: 'Invalid file',
    invoiceGeneratedSuccessfully: 'Invoice generated successfully',
    errorGeneratingInvoice: 'Error generating invoice',
    errorLoadingOrder: 'Error loading order',
    orderNotFound2: 'Order not found',
    
    // Statistics Page
    refresh: 'Refresh',
    totalCustomers: 'Total Customers',
    totalRevenue: 'Total Revenue',
    averageOrderValue: 'Average Order Value',
    
    // Status and User Management
    status: 'Status',
    working: 'Working',
    done: 'Done',
    toggleStatus: 'Toggle Status',
    selectAll: 'Select All',
    deselectAll: 'Deselect All',
    generateSelectedInvoice: 'Generate Selected Invoice',
    selectItemsForInvoice: 'Select Items for Invoice',
    itemsSelected: 'items selected',
    selectedItems: 'Selected Items',
    usersManagement: 'Users Management',
    manageUsers: 'Manage Users',
    deleteUser: 'Delete User',
    confirmDeleteUser: 'Are you sure you want to delete this user?',
    userDeletedSuccessfully: 'User deleted successfully',
    errorDeletingUser: 'Error deleting user',
    noUsersFound: 'No users found',
    userOrdersCount: 'Orders Count',
    cannotDeleteUserWithOrders: 'Cannot delete user with existing orders',
    usersManagementNote: 'Note: Users with existing orders cannot be deleted',
    orderSummary: 'Order Summary',
    close: 'Close',
    viewOrderDetails: 'View Order Details',
    clickViewDetailsToManageItems: 'Click "View Order Details" to manage items and change status',
    clickGenerateInvoiceToManageItems: 'Click "Generate PDF Invoice" to view order details and manage items',
    storageInformation: 'Storage Information',
    estimatedDataSize: 'Estimated Data Size',
    browserStorageUsed: 'Browser Storage Used',
    browserStorageAvailable: 'Browser Storage Available',
    usagePercentage: 'Usage Percentage',
    storageDetails: 'Storage Details',
    storageLocation: 'Storage Location',
    browserIndexedDB: 'Browser (IndexedDB)',
    browserLimit: 'Browser Limit',
    chromeLimit: '~80% of available disk space',
    firefoxLimit: '~50% of available disk space',
    safariLimit: '~1GB (iOS) / ~5GB (macOS)',
    edgeLimit: '~80% of available disk space',
    variesByBrowser: 'Varies by browser',
    dataPersistence: 'Data Persistence',
    localToEachDevice: 'Local to each device',
    backupMethod: 'Backup Method',
    useExportImportFeature: 'Use Export/Import feature',
    ordersByCategory: 'Orders by Category',
    ordersByMonth: 'Orders by Month',
    topCustomers: 'Top Customers',
    orders: 'orders',
    uncategorized: 'Uncategorized',
    importantNotes: 'Important Notes',
    dataStoredLocally: 'Data is stored locally in your browser only',
    clearingBrowserDataWarning: 'Clearing browser data will delete all orders',
    dataDoesNotSync: 'Data doesn\'t sync between devices',
    regularExportsRecommended: 'Regular exports are recommended for backup'
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'ar';
  });

  const t = (key) => {
    return translations[language][key] || key;
  };

  const toggleLanguage = () => {
    const newLanguage = language === 'ar' ? 'en' : 'ar';
    setLanguage(newLanguage);
    localStorage.setItem('language', newLanguage);
  };

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, t, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};
